name: Chromatic

on:
  push:
    paths:
      - 'packages/waystone-*/**'
      - '.github/workflows/coverage.yml'
      - '!**/*.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  chromatic:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        id: setup
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install
      
      - name: Build Packages
        run: pnpm run build
      
      - name: Publish storybook if a publish happens
        id: chromatic
        uses: chromaui/action@latest
        with:
          storybookBuildDir: 'apps/stories/storybook-static'
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: 'main'
          skip: 'dependabot/**'