name: Publish Codecov

on:  
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    paths:
      - 'packages/**'
      - '**/package.json'
      - '.github/workflows/coverage.yml'
      - '!**/*.md'
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - '**/package.json'
      - '.github/workflows/coverage.yml'
      - '!**/*.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  coverage:
    name: Upload coverage to Codecov
    runs-on: blacksmith-4vcpu-ubuntu-2204
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        id: setup
        uses: useblacksmith/setup-node@v5
        with:
          cache: 'pnpm'
      
      - name: Install Dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm lint:release

      - name: Run tests and collect coverage
        run: pnpm test:release

      - name: Upload results to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          