name: Coverage Reporting

on:  
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    paths:
      - 'packages/waystone-components/**'
      - 'packages/waystone-core/**'
      - 'packages/waystone-utils/**'
      - '.github/workflows/coverage.yml'
  push:
    branches:
      - main
    paths:
      - 'packages/waystone-components/**'
      - 'packages/waystone-core/**'
      - 'packages/waystone-utils/**'
      - '.github/workflows/coverage.yml'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  coverage:
    name: Upload coverage to Codecov
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'
      
      - name: Install Dependencies
        run: yarn

      - name: Run tests and collect coverage
        run: yarn test:release

      - name: Upload results to codecov
        uses: codecov/codecov-action@v3
          