name: Publish Packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'
      - '.github/workflows/release.yml'

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node.js
        id: setup
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install
      
      - name: Build Packages
        run: pnpm run build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          commit: 'chore: version packages'
          title: 'chore: version packages'
          publish: 'pnpm exec changeset publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}